name: 'Screenshot and Diff'
description: 'Create screenshots of a set of URLs and run diffs between old and new versions'
runs:
  using: 'composite'
  steps:
    - name: Set up node
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: cd $GITHUB_ACTION_PATH && npm install
      shell: bash
    - name: Create screenshots & diffs
      run: cd $GITHUB_ACTION_PATH && npm run start
      shell: bash
    - name: Set screenshot path
      run: |
        echo "screenshot_path=$GITHUB_ACTION_PATH" >> $GITHUB_ENV
      shell: bash
    - name: test2
      run: cd $GITHUB_ACTION_PATH && ls -la
      shell: bash
    - uses: actions/upload-artifact@v2
      with:
        path: ${{ env.screenshot_path }}/screenshots/

