name: 'Screenshot and Diff'
description: 'Create screenshots of a set of URLs and run diffs between old and new versions'
runs:
  using: 'composite'
  steps:
    - name: Set up node
      uses: actions/setup-node@v2
    - name: Install dependencies
      run: npm install
      shell: bash
    - name: Create screenshots & diffs
      run: npm run start
      shell: bash

